### ISSUE TITLE
feat: contract read/write/simulate

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#10]
### Describe the Feature Request
Develop the code to read, write, and simulate transactions on the blockchain for the score system.

- [x] Study the Karma Project:
- Investigate the technologies used by the Karma project to communicate with the blockchain (if any).
- Determine if we need to install new technology or if we can leverage the existing tech from the Karma project.

- [x] Understand Smart Contract Functions:
- Identify the necessary functions in the Smart Contracts (Resolver, EAS, and Trustful Score) that need to be imported into the frontend.

- [x] Develop the Code:
- Write the code to read, write, and simulate transactions on the blockchain using the identified functions.
- Ensure the code is adapted to handle these functions accordinly

**Comment by RafaDSan** [comment]
issue closed by the commit [517cee6](https://github.com/show-karma/gap-app-v2/commit/517cee6204fbdc2108c4ddfb4b09cbaeeb2d4abb)
