### ISSUE TITLE
feat: organize folder architecture

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#2]
Read all the issues and imagine their file names and file locations following the Gap repo pattern.

Definition of Done:
- [x] print here in the comment the tree view of the file folders and files that will be created and your logic behind it

**Comment by heronlancellot** [comment]
## Explain the actual structure 

### Explaining the actual structure of the files/folders in the application.

The structure of the repository in app/
<img width="331" alt="image" src="https://github.com/user-attachments/assets/12f81d68-e4d4-46ab-9f1b-56152532ddc3">
- inside the grants/page.tsx
    - It's rendering the ProjectGrantsPage.


<img width="332" alt="image" src="https://github.com/user-attachments/assets/68f02766-2440-409b-bbc7-74149b86b446">

- inside the components/Pages/Project 
    - Have the ProjectGrantsPage component.
 
Looking for the structure in Components/Pages/Project/Impact
 - We can see that we have a few components and the index is the main component that app/project/[projectId]/impact uses to render the page. We want to build a structure similar to this.
 
<img width="308" alt="image" src="https://github.com/user-attachments/assets/acad9c2d-1484-4a53-b6c8-74943801ca88">

-----

### Looking at what we're going to build

After analyzing the current project folder struct, I point out some things that will lead to the proposal of how we should be building our feature architecture.

#### Folder Tree

<img width="920" alt="image" src="https://github.com/user-attachments/assets/228e054e-d488-4210-9ef7-ce79e35a3610">


- We must have some variants to make the Card Review Collection editable or not (stars)
- We must also check whether it is possible for the user to submit the review or not. Creating some structure for that too.
