### ISSUE TITLE
feat: new menu tab: Review

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#3]
Definition of Done:
- [x] Create a component that will be opened by clicking a new tab inside the Grants Project as the last tab of all on the far right.

![image](https://github.com/user-attachments/assets/64e229a6-18c3-448b-b9ce-52886494c62e)

**Comment by heronlancellot** [comment]
[PR](https://github.com/blockful-io/gap-app-v2/pull/1)
