### ISSUE TITLE
feat: navbar to display each review and score

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#4]
This feature is the navbar component with the timeline of all reviews made by the grantee.

Definition of Done:
- [x] Create the molecule for the mini-review card containing the date the review was made and its score.
- [x] Create an organism with a horizontal scroll that can support multiple mini-review cards, ascendent order based on timestamp (newest right, oldest left)
- [x] Those molecules are clickable and will eventually display the spoiler with another organism
- [ ] There is a button on the far top right of the component that will change the viewpoint of the component from "viewing badges" to "reviewing badges". It will require the user to connect the wallet and match the same address as the owner of the grant.

All data should be mocked and there should be enough date to show the horizontal scroll working.

![image](https://github.com/user-attachments/assets/d4c91617-4b96-47ec-aaec-203e8bbd1c3d)

**Comment by heronlancellot** [comment]
Closed by [#2 ](https://github.com/blockful-io/gap-app-v2/pull/2)
The "viewing badges" to "reviewing badges" need prerequisites and some data to be finished. Because of that we will move that task to another time.
