### ISSUE TITLE
feat: review write variant component with submit review button

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#8]
This feature is about the Navbar & CardReview component 

## Definition of Done:
- [x] Clicking in `Review` button will change the mode of the organism to `Write a new Review`.

### Write a new review
- [x] All new reviews will have the default badges with a 0-star rating.
- [x] Change the text 'All reviews from....' to "Write a review" 
- [x] Remove Review button and switch to Close icon.

### Submiting a new review
- [x] After submitting a new review, return to reading mode review.

**Comment by heronlancellot** [comment]
Closed by this [PR](https://github.com/blockful-io/gap-app-v2/pull/4). 
Additionally, a toast was added when the user submits the review.
