### ISSUE TITLE
feat: subgraph with react queries - scripts and schemas

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-gap-contracts#9]
### Describe the Feature Request
To accurately display the grant's score, we need to fetch the user's review from the blockchain. This review will be generated using the Ethereum Attestation Service (EAS) and its subgraph.

- [x]  Study the Karma Project:
- Investigate if the Karma project connects to any endpoints.
- Determine if it's feasible to use the same technology to fetch data from the EAS subgraph.
- Decide if any changes are necessary for integration.

- [x] Install TanStack Query:
- Install TanStack Query to utilize React Query for handling the data fetched.
- [x] Create a Query: 

- Develop a query to fetch the Score Attestation from the EAS subgraph.

- [x] Script Development:
- Write a script to correctly execute the query and fetch the required data.
- The URL paremeter of axios should be dynamic the subgraph endpoint will change from network to network

**Comment by RafaDSan** [comment]
issue closed by the commit [517cee6](https://github.com/show-karma/gap-app-v2/commit/517cee6204fbdc2108c4ddfb4b09cbaeeb2d4abb)
